bases:
  - ../base
namespace: backend
resources:
  - secrets/sealed-secrets.yml
  - certificate.yml
configMapGenerator:
  - name: configmap
    namespace: backend
    literals:
      - MYSQL_POOL=20
      - ELASTICSEARCH_HOST=elasticsearch-es-http.eck
      - ELASTICSEARCH_PORT=9200
images:
  - name: jkubacki/jobs-api
    newTag: "2d9bad5"
