bases:
  - ../base
namespace: cv
# resources:
#   - certificate.yml
configMapGenerator:
  - name: configmap
    literals:
      - node-env=production
images:
  - name: jkubacki/cv
    newTag: 2ffd379
