apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jkubacki/jobs-kubernetes
        revision: HEAD
        files:
          - path: "tools/metrics-server/values.yml"
  template:
    metadata:
      name: metrics-server
    spec:
      destination:
        server: "https://kubernetes.default.svc"
        namespace: metrics-server
      project: default
      source:
        helm:
          values: |-
            {{values}}
        repoURL: https://github.com/kubernetes-sigs/metrics-server.git
        targetRevision: v0.6.4
        path: "charts/metrics-server"
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - CreateNamespace=true
