apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# First do kubectl create -f https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-54.1.0/charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
resources:
  - https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-54.1.0/charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
  - https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-54.1.0/charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
  - https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-54.1.0/charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
  - https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-54.1.0/charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
  - https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-54.1.0/charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
  - https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-54.1.0/charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
  - https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-54.1.0/charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml
  - conf/application.yml
  - conf/grafana
  - conf/alertmanager
  - conf/prometheus
