apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv
  template:
    metadata:
      labels:
        app: cv
    spec:
      containers:
        - name: cv
          image: jkubacki/cv:kustomize
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 768Mi
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: configmap
