apiVersion: v1
kind: ConfigMap
data:
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
metadata:
  name: argocd-cm
  namespace: argocd
