apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - "namespace.yml"
  - "install.yml"
  # - "ingress.yml"
patches:
  - path: "argo-cd-cm-patch.yml"
    target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
