apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jkubacki/jobs-kubernetes
        revision: HEAD
        files:
          - path: "tools/ingress-nginx/values.yml"
  template:
    metadata:
      name: ingress-nginx
    spec:
      destination:
        server: "https://kubernetes.default.svc"
        namespace: ingress-nginx
      project: default
      source:
        helm:
          values: |-
            {{values}}
        repoURL: https://github.com/kubernetes/ingress-nginx.git
        targetRevision: helm-chart-4.10.1
        path: "charts/ingress-nginx"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
