---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: mysql
  namespace: mysql
spec:
  encryptedData:
    mysql-password: AgAa10w8v+G8WblVnFNWNYfHw90lx0+JbhykPtOdaYrhqeTGYaJgfG6VkiGlCBVdIF8yu6IcfFpi6roKctO73JdUiOw3dAHIjYoHgzzv6AWY64Jc0Mn4ZPNC0hOKgIMft3O6R/r0iNe3TDbSYbK03Q4mAQPYZhj0IpQnizVuWcPcZ2ipWRbP7igV8YzyiGTAxrWtp7nJZ8ue4VsInFv/Ghdw8v2+s6ZnA1z/U2AzPDXJ+5//w/LW28+cpCKf3AmKV9fJ3k+QJI+C17GuuzM1idTZM9NBWABMua9lS2pm0dH40lO0yP/PiRZ4FTUu5V3RJiiqH4WEczLjHcZVFbxqJNuUEbfZsK6M/QPTiGOHe5BmPZU0IZHpV3jZdNtZ7jZgE4qtJBFuyzpGw64NcQfIMO/F/KmUpB3r7lShJiMqFELw78JF1+gL7BOfi38AUScHLDlU9Fh8VpHusU6qh1rxvCSruLIXCzrbxk3xguojm6JoLpwymrw/NZ6GUy+VxY9GPt4UnSq07MyEJwu+IT5HShGG2p9jSgzP8mcRkN48fAIUj5P8MyZ9UhhCsezahqAwufstiH2fteVwzsULS9GdrvYk8p5cMPELljzNOTegQV1h1FkMVNpET9MzeJGmMYH6VA8GmFoTngkcxarN/sG0Ud/9KpZjeStJ3FB6i8gjE35OVwMwzzsMe/M9w+apX3tqDqCNOhUA6t1eOg+Dt53GT2Mu1bzYK/qe8zGE3xfTqihPdA==
    mysql-replication-password: AgACjgUoLYG1629sALzObjolCEITl351SSs/J1/UXHSJwV9NOCZT+t14CtOH2LMJ8pes4IVcRDBV7ydHHIWv/NxVbBG+0W2jm2Nc/YGZh68Xzsn8lx5o44EviklXBhk1fjAa6V0eX21ggcUxACGfsmrQ7nGnFCY1JLmRYvweTpOGE8/RNhlTgymdVeClAFCl2ve4cD3QLI37zN49A3KjjuuoZzLGk8uzRgGPaSOTWmOVv+hQTLeRwrOofdYuwNtd0B9u68MJGdoW48aNysmko+dp/gK4VVSewNZdD7xbXPoZptHEiK8EMCgo4GId+O4/x/IVff/3kp8oDgu3ZyCnHyFp0fAYvs+iJoiw2cZAa/ZszBoutlI2Nsuqfzr7DSkmLAn2cwZF36hrpFymh3Bqs2Qabap3+xmgFRg6PeLfqsmRkfHHK1VRnGaSCLc6gmtVCIrdW7tWR+lRSHEjk7T8r2AD9RYMrBkAFC87K9SuPTe9IUlgMVG6kfZeMio2h4q/PBmhwzxJQVFOXbbmD3/cRtDSHGuD/fqgetqxEBvHRS+TFTg7VUgaa/MU0w2A4fsiOYi6VvxzS/H4agbQCRQlSfmSUjZb7se1Tild5IvCgs8+NbJkt4+YyTE2lpO/3LDQLRgH2pthtZ1nBVIN7lI2+DzouU3W+YKYOLHBCc6KWNuvzLKEqr38a01jEJlwlUgLW01T8SJkm3GZKaJ527SThOtEfkVurZ1bvpDQeGDZRIyxyA==
    mysql-root-password: AgDV9PXw0rLwBJ0JZ2VXvN6LRe6wuCmdWgYITAmWOIC9ZTjujbR+FCBdf4AcTPGnk5am4Mc0Z78ZrNWzUcYTi8B/x1/SqbzLdH3fTfIvkV8pELaA7A4Fr77Xey2CUNDXtFkI1oRdLp2a1fM1iQYVVfIj4TGww10K3RG0x/LoQhouxELy14lbM9yzLJLjVAGQGkY8NC/UE9mhUbXYjk7SizLgNMTfgj41e88hS3xLR7eLqcFNI5egdtZa7BY4nn7a4cOurTHlg3OLGXFzA0Va4ZzxBaUxJc5R2YZe4bdjHS3xFyZUFw2wWC2L9GGQwJTI9u7bkXInUI9yLXssLX8IwE0lFCJE0iz9X3rTFXjo0BjXNXcx9D1j6m1zSZzDYksdmNwlIHtLR/BLDHXxZvJBmv/UX9kNG+c2AUFJS7E0xLijAbxjlh0RdiX54aHTEAAI2lXiowQdp73l54niNCFvmR7/7gH2HX5T9SgbLszHu1u4Pi3BXcAwUH0py8uqYpfrUCOSi5P9m/6IoLHWwQgyIMYYM9UGrUQRrEtg2SopNcjPjA2L9C+Byq9Dp2DkzRH2ZYsHF+8D0FN+uezERC2z3TglfOAnYog02ROvjMMTbWVH8UcoG5+ebrJtxDUEGeKNkdd67Tv8Lcgu/jnUB9PNpduL44qQMTtZfgXiA5+whwPutRTjBRDl6C8XnEwsE3LInZu6+DQ9bFCs4ISPxVqDZXK/8bKQVMBdSYO53lyCGJHQPA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: mysql
      namespace: mysql
    type: Opaque
