apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rails
  namespace: default
spec:
  dnsNames:
    - api.demo.jakubkubacki.com
    - www.api.demo.jakubkubacki.com
  secretName: rails-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
