bases:
  - ../base
namespace: backend-demo
resources:
  - secrets/sealed-secrets.yml
  - certificate.yml
  - "cronjobs/reset-seeds-when-no-recent-activity.yml"
patches:
  - path: "patches/ingress.yml"
    target:
      kind: Ingress
      name: rails
configMapGenerator:
  - name: configmap
    literals:
      - MYSQL_POOL=20
      - ELASTICSEARCH_HOST=elasticsearch-es-http.eck
      - ELASTICSEARCH_PORT=9200
images:
  - name: jkubacki/jobs-api
    newTag: "8dcc2c31"
