apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jkubacki/jobs-kubernetes
    targetRevision: HEAD
    path: apps/backend/production
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
