apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
  namespace: default
spec:
  dnsNames:
    - demo.jakubkubacki.com
    - www.demo.jakubkubacki.com
  secretName: frontend-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
