bases:
  - ../base
resources:
  - certificate.yml
  - "secrets/sealed-secrets.yml"
namespace: frontend-demo
configMapGenerator:
  - name: configmap
    literals:
      - node-env=production
      - NEXT_PUBLIC_API_PATH="https://api.demo.jakubkubacki.com/api/v1/"
patches:
  - path: "patches/ingress.yml"
    target:
      kind: Ingress
      name: frontend
images:
  - name: jkubacki/jobs-frontend
    newTag: "demo-560cc101"
