bases:
  - ../base
resources:
  - certificate.yml
namespace: frontend-demo
configMapGenerator:
  - name: configmap
    literals:
      - node-env=production
patches:
  - path: "patches/ingress.yml"
    target:
      kind: Ingress
      name: frontend
images:
  - name: jkubacki/jobs-frontend
    newTag: "demo-e2518c9"
