---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: backend
spec:
  encryptedData:
    auth: AgCfX3lsxiioyAiwkVX5RXsi/5c+PsqoHqxYnJXI8B8JAS0wdhi1rHiGNimPA1jNn+vDj4xq8lreSiH0MW87dJC/L0vufdN10PfttQsGjOPOMtofHI18lpr2irtqQZg/tEiTvHPFaBRrgQV0A8xQzZRcQQytbQKldMlT2g7BYJJ7OrownPemWVdJWjH/J9NvuhWnm6uGoWjuC+vN/5EC53DYaSduSjQuGNfEJDQApTrwzVwLtf1qAyOqfInAhpMPpRa4OswqL/MY3U0yVe+LnByETqTGzFEvG4WqTx58moG4JXLJPLmTIjb3mTWOZxmDAVHw7bEiypNp+2cka0TThsWFnFo+4ydRqMdKCv+4f/CVkuvVNUcRzxuR93zIwkKj3wHTfnLGgoIH4m8b/ajYBpCJNyJ6yxvHA3EfFjhPTkiBROXaXxCMgzWsVCB4suDbIcVe5qcIqZmZdYBy2tiMl5frCfJODBj6HSFHm2EkGN77WG91uUas4UuA0SL7d2QcPtfoLKJ71k3LfBCJFK2onHZhDDDUiHizmp/Md/VIJ6tc0B4Eu78SuC6AxgIJzqoE5zLmCTZlRVjUHASQmze8ayPpX0kXrfc7OF9qMufkOJofVE+a1H6W1VLyIrLAGsFt1vx7LE+wFtJXbyYVpAEMD5Pssad0z1An2oIzHV0gGIkeBGvtVfjMKVOY2FqLbBRHOOq0QXor4BDfr64xkmwSCKBzVVTB8bkoAOGMy+ua39ba+/cKa5JL/CYe//zIbGYC+w==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: backend
    type: Opaque
