apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager
  namespace: default
spec:
  dnsNames:
    - alertmanager.kubernetes.jakubkubacki.com
    - www.alertmanager.kubernetes.jakubkubacki.com
  secretName: alertmanager-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
