apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jkubacki/jobs-kubernetes
    targetRevision: HEAD
    path: tools/eck
  destination:
    server: https://kubernetes.default.svc
    namespace: eck
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: false
