---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    admin-password: AgCHzgPzCBEmaBku7eeZNIP8RF6ZYBbsGH5lNHwCFwyqFeZPm6ogx7td9h6TTTbw4Rsl4x9KhF5Pv6AToh/RdB5l6HeXQNoB5RMUBbwTZlWRfg/ySMuIJmhs+8WbkJ/QfitvFcPPbZg8WJeuvs1uighwx9/hhNozQ8oWJ/qRviQxeXZ0lECWVhUJ+cQ4A1c6p5qKQ35ozicJ6Pxkl0yOEZztXSMc+cL+7qN07QWETp5ZkXNC/Ry6bKXjmBEaYOGZ84FnbICRsToG1dB4nznhKF829x6cSR0cD6FOG3juYnp5SnRxtQNE2NhK5PTD3rORrKkDMrvg4ROaVgUDnKtqdXowTStm2R9i5gtyV+FKTVTBCkoNBLwMdohntLPrkLlrnximo/66jmVTydQ4WYT9ECYPNeP9mjmm3+R1WKvmRzVl5rMx1egjZJ9NwqxInWHL/kJ70OGwUpIsgGHdJ/xg30RLK61TvM+dBkiEEPgW7hdUH3lQq2Iw2SNvWWfzCSXUrmE+6UnFrZCVx/GhPXecVr0GvkPo/zKXLMUH7bQ7xzq6TePyNUyxYAR78sp8ZSrYWJVdPRN0DKkKUNCarklsikJG2woOTS22ZYQzYseBYj2uVneJYfQSx+iH+6n1orocJlci5lhj9l0EQ53gb2vo+NyboEXQ3AehiwOpu8colyRazDZIAMWcAUvAqnQY9C7hj0MQRuxoK4CVyMEi94xoy6Oy1M75gnyEe09tGsq/59AuwmGKMbt4OAgj076t5FTm5vd2GrwdfcV05mrmZp0JmMgr
    admin-user: AgDam/nERLkbOwpjH/4mhYjjCdW20zih5U6DeCDadS2CBVkVxnhJO8US3GpvQPhrwewYj0pjDems5yCwk9r47ml5FjKzumXwpwsf0lVGfK5HzFiguKvqzXI/YR89dX/2Lpcl8kexVZ/N+JubzQl61f0JkHw2PeTilW7HXstH1E/8BpHCACDo1Zp+B3IOHyic9BHpEHUT8/x1nSgvC9mMG+csaXjiZjeYbNvWzXgPZYLOYMaVCdyQ0Me5HI4fF6tup/fiN13lZ++kGwSKTG3/ql+VUp+vyy9g9eU/PUF0MBJH9tNy6ZieUDw+Jd8kqVh1nswNgGMuSZvbLwDmpcb1Qp0WzrEfBgfrhmOemECswCHBvfQnHivNRlcnS+s2aet2tcSrpmPlCu3LB+lbgmHw8FdCHu6T6VH73n+QTueiHY1bQzN7xJJ+KAEv6r6BmlVJyPg1+v7PoCkEeq9fYxTIMDxR+AaGqxtqfWl7JHOnmgZ3fqz7RXzYEUuVrt8CAh0lcymatOFhprdyGeUuoMKgpqKIComJZcbOuVgFWNfIn2XMUCcdCOVAkbKhfqidCl1PLp4VeZwS9CeXLBs1qrPg7nNvrrLe6jWmU8Tpz/FEoqIB6DWdjp8pJq7AbU6qNlXGOfeMFffrE02VWhTcKN5mHtfWZAOKdLZ1RmFCz6FDrKQWgLI1ymuZx6HHlqasE0T4SoEDmCjd5HRKw8hFr/0Fpc12iJI0Rw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: kube-prometheus-stack
    type: Opaque
