apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: default
spec:
  dnsNames:
    - grafana.kubernetes.jakubkubacki.com
    - www.grafana.kubernetes.jakubkubacki.com
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
