---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: secrets
  namespace: frontend-demo
spec:
  encryptedData:
    NEXT_PUBLIC_BASIC_AUTH_PASSWORD: AgAtOZ6to6k9EDCvgQFABcEzFb88+NKPfEYynmFkp3hio6oBunQlABrVFsdJ+zbRUyfQcExS0qkmojayMyV+EYW4J1h2iSY+p2N2HLmjpcYEd4m9/EHl0Ip8X+ydt8BJ5kJaWnxZNsXGm0zax9K0hTx3wO9cC22YjFZn50NDqFskL8Wc1wlFY/Irx3SKV+iJcoX3pUmugO4tQrY/43aMsGHJmuZ9DiBTT9z63ccmmOQK/Mj5WUYw8+hFYNV78sPg6lIeyC2eG26jmPXCX8xsforSslFUNbq5f7+Qxi8Oyt4ntL1vTOsrNV3MTBZf+HXAFUM08kyNVZsAM8IxzkGaqD+Q+P4lHofqKPPxnd6/C8/2ThZ3VtyaH8lcsF5MVnrK5ChuiitFA1ic00H3+DmNd/DbP2h89cPfAAAq28vK1c1gzgCjcgnX//cYy9dp9sgE1iGtEDZgStCSB/l2/6HYHYHC0RophbG5UNzsWcrUdTSgmh8MSyTFUEwPtnQzyKT9BLycbrmEh9RHyDP1VeBd+FVWnmNkYwO/BIJxizSyCpBlKfw6L5sMNJ5fxzQQyWVBFSUEbN6/leBvwsJfKY3CsNyQ2C3gL+YZgr+u5ePEU6hpP4k8rJfhDLuKa/+hGcE0pEfqFpCCpAeurxRSEFifbK0rgPyWoSRYQGIJf7TBf9PFd8z7qBYeRHlOSdxhePX+XOC8a0GR
    NEXT_PUBLIC_BASIC_AUTH_USERNAME: AgCRhSL1woBjKPDL5lVsgfcN3VbnzllIaoxp0ib1inWdm4S+rOEjsKRhVj7Gmje9m1H8KsJMBftO86RL8dr0kVqagJDWN8/nrh9ppo9brauJhLWIx+jPfwjQFkZJxaSU1fWwmLkZTtSw72Xzyr0CecsFsMt1H0feDDDx/u30p25zNyFNyun66Gt7RO1rLFvBWzQG5Mfd5uJXTEhJ2VZVoP/+5H6OhGzWIs2jnZMyNWTucSUQ78Oqp7PpNL+evRPELy18VMC0ZKntb2ndELcCIy8E0pQnqOBbndUFMy8JGYn3RHX1hUok16RiyRuqgY/r61XNaYpD5Oboh+/oVrdQKzW4mOyDY2krZTp8vlIcbp51vgkAv/miIt3TkL1c1VII89SARtGzeUEiNM4KSTWI7OK/JR16CbrqnNbuStQUQXX+FfGgD0VANO87t/VJV12aKgGR+xhzslRHk22U3wS6zyEC2ZxQhw6b0C1RvPIlUX0QQWieuOdXjt4cfuf1w55rY+9CCi0hpxYSMUAfUN6TmhgOehRbak/q5gHmtVhLzEbvsCprHzOt1mNe3IHZPloB/hxQVcbc1iNFmX6/qkDyX59lx/mH/mDBVTDcZO5Cr0j+kFNjafXlmQTmRmakDVuI463oKVaAmemHBNnFQXzWYzYqX0FG5+vCs8RoNxcv7Xd1FyuBPTqVqVj+AD0/2+xAIX4dv8Zv
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: secrets
      namespace: frontend-demo
    type: Opaque
