bases:
  - ../base
namespace: frontend
resources:
  - certificate.yml
  - "secrets/sealed-basic-auth.yml"
configMapGenerator:
  - name: configmap
    literals:
      - node-env=production
patches:
  - path: "patches/ingress.yml"
    target:
      kind: Ingress
      name: frontend
images:
  - name: jkubacki/jobs-frontend
    newTag: "production-091a146"
