bases:
  - ../base
namespace: frontend
resources:
  - certificate.yml
  - "secrets/sealed-basic-auth.yml"
configMapGenerator:
  - name: configmap
    literals:
      - node-env=production
images:
  - name: jkubacki/jobs-frontend
    newTag: "production-e2518c9"
