bases:
  - ../base
namespace: frontend
resources:
  - certificate.yml
  - "secrets/sealed-basic-auth.yml"
  - "secrets/sealed-secrets.yml"
configMapGenerator:
  - name: configmap
    literals:
      - node-env=production
      - NEXT_PUBLIC_API_PATH="https://api.jobs.jakubkubacki.com/api/v1/"
      - NEXT_PUBLIC_ENVIRONMENT="PRODUCTION"
patches:
  - path: "patches/ingress.yml"
    target:
      kind: Ingress
      name: frontend
images:
  - name: jkubacki/jobs-frontend
    newTag: "6c6273a"
